# Generated by Django 5.2.8 on 2025-11-19 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Código')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='Fabricante')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantidade')),
                ('minimum_stock', models.IntegerField(default=5, verbose_name='Estoque Mínimo')),
                ('processor', models.CharField(blank=True, max_length=200, verbose_name='Processador')),
                ('ram', models.CharField(blank=True, max_length=50, verbose_name='Memória RAM')),
                ('storage', models.CharField(blank=True, max_length=50, verbose_name='Armazenamento')),
                ('screen_size', models.CharField(blank=True, max_length=50, verbose_name='Tamanho da Tela')),
                ('camera_resolution', models.CharField(blank=True, max_length=50, verbose_name='Resolução da Câmera')),
                ('operating_system', models.CharField(blank=True, max_length=100, verbose_name='Sistema Operacional')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Cor')),
                ('voltage', models.CharField(blank=True, max_length=20, verbose_name='Voltagem')),
                ('dimensions', models.CharField(blank=True, max_length=100, verbose_name='Dimensões')),
                ('resolution', models.CharField(blank=True, max_length=50, verbose_name='Resolução')),
                ('connectivity', models.CharField(blank=True, max_length=200, verbose_name='Conectividade')),
                ('ports', models.CharField(blank=True, max_length=200, verbose_name='Portas')),
                ('material', models.CharField(blank=True, max_length=100, verbose_name='Material')),
                ('weight', models.CharField(blank=True, max_length=50, verbose_name='Peso')),
                ('status', models.CharField(choices=[('IN_USE', 'In Use'), ('MAINTENANCE', 'Maintenance'), ('AVAILABLE', 'Available'), ('BROKEN', 'Broken')], default='AVAILABLE', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(related_name='items', to='categories.category')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=10, verbose_name='Tipo de Movimentação')),
                ('quantity', models.IntegerField(verbose_name='Quantidade')),
                ('date', models.DateField(verbose_name='Data')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='items.item', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
