# Generated by Django 5.2.8 on 2025-11-19 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('IN_USE', 'In Use'), ('MAINTENANCE', 'Maintenance'), ('AVAILABLE', 'Available'), ('BROKEN', 'Broken')], default='AVAILABLE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ManyToManyField(related_name='items', to='categories.category')),
            ],
        ),
    ]
