# Generated by Django 5.2.8 on 2025-11-14 18:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ItemType",
            new_name="ItemCategory",
        ),
        migrations.AlterModelOptions(
            name="itemcategory",
            options={"verbose_name_plural": "Item categories"},
        ),
        migrations.RenameField(
            model_name="item",
            old_name="type",
            new_name="category",
        ),
    ]
