# Generated by Django 5.2.8 on 2025-11-15 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('items', '0002_rename_itemtype_itemcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='categories.itemcategory', to_field='name'),
        ),
        migrations.DeleteModel(
            name='ItemCategory',
        ),
    ]
