# Generated by Django 5.2.8 on 2025-11-15 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome do tipo')),
                ('description', models.TextField(max_length=200, verbose_name='Descrição do Tipo')),
            ],
            options={
                'verbose_name_plural': 'Item categories',
            },
        ),
    ]
